pollVersionStatusInterval: 3000
githubUrl: https://github.com/
dashboardUrl: https://dashboard.aerobatic.com
awsCertificatesEmail: no-reply@certificates.amazon.com
userConfigFile: .aerorc.test.yml
deployTimeoutSeconds: 360
# The URL to the bucket where the Aerobatic themes reside
themesBaseUrl: https://aerobatic-themes.s3-accelerate.amazonaws.com/
